defmodule AshWaha do
  @moduledoc """
  Ash extension that adds a `whatsapp` DSL block to resources, plus changes
  that wrap `ExWaha` calls so they participate in Ash actions, policies, and
  audit.

  ## Status

  Skeleton — the DSL is defined and the `SendText` change is functional, but
  the auto-injected actions are not yet generated by the transformer. Use
  custom actions with `change AshWaha.Changes.SendText` for now.

  ## Intended shape

      defmodule MyApp.Whatsapp.Profile do
        use Ash.Resource, extensions: [AshWaha]

        whatsapp do
          account {MyApp.Whatsapp.Accounts, :for_profile, []}
          session_name expr("profile_" <> ^id)
          on_event :message, MyApp.Whatsapp.InboundHandler
        end

        actions do
          update :send_welcome do
            argument :greeting, :string, default: "Welcome!"
            change AshWaha.Changes.SendText, text_arg: :greeting
          end
        end
      end
  """

  use Spark.Dsl.Extension,
    sections: [AshWaha.Dsl.whatsapp_section()],
    transformers: []
end
